using System;
using System.Collections.Generic;
using AutoService.Domain.Building;
using AutoService.Domain.Points;
using AutoService.Domain.Traffic.Routing;
using AutoService.Presentation.Building;
using AutoService.Presentation.Points;
using AutoService.Presentation.Traffic.Routing;
using AutoService.Services.Config;
using AutoService.Services.Traffic;
using UnityEngine;
using UnityEngine.Serialization;

namespace AutoService.Presentation.Traffic
{
    /// <summary>
    /// Scene markup of one location: its points (two parking entrances and the service points with their buffers),
    /// its one-way road graph (<see cref="RoadNode"/>s below this object), spawn/exit nodes, entry queue slots and parking
    /// slots. Resolves engine-agnostic <see cref="CarDestination"/>s into road nodes and builds the <see cref="RouteGraph"/>
    /// cars drive on.
    /// </summary>
    /// <remarks>
    /// Every point's Car Spot carries a <see cref="RoadNode"/>, so a point is just another node of the graph.
    /// <para><b>Build plots.</b> <see cref="ServicePoints"/> and the parking slots list EVERYTHING the location can have,
    /// built or not; a <see cref="BuildPlotView"/> covers what is not built yet. A point is built at the start when it is
    /// not inside any plot's Target; the lot starts with the slots no plot covers (the covered ones are the last slots).</para>
    /// Whitebox layout v3.1 is generated by <c>AutoService → Whitebox → Build Location 1 Roads</c> (GDD §3).
    /// </remarks>
    public sealed class LocationLayout : MonoBehaviour
    {
        private const float SlotGizmoRadius = 0.6f;

        [SerializeField]
        [Tooltip("Location id; every point of this location gets it as LocationId, e.g. \"loc1\".")]
        private string _locationId = string.Empty;

        [SerializeField, FormerlySerializedAs("_parkingExit"), FormerlySerializedAs("_barrier")]
        [Tooltip("Parking entrance barrier reached from the road (Service Type of kind Barrier).")]
        private ServicePointView _mainEntrance;

        [SerializeField]
        [Tooltip("Parking entrance barrier reached after a service (Service Type of kind Barrier).")]
        private ServicePointView _serviceEntrance;

        [SerializeField]
        [Tooltip("Service points of the location (wash...), built or not, each with the same number of Buffer Slots. Not the entrances.")]
        private ServicePointView[] _servicePoints = new ServicePointView[0];

        [SerializeField]
        [Tooltip("Road node where cars appear; its forward is their initial heading.")]
        private RoadNode _spawnNode;

        [SerializeField]
        [Tooltip("Road node where leaving cars drive to and disappear.")]
        private RoadNode _exitNode;

        [SerializeField]
        [Tooltip("Entry queue lane slots (road nodes); element 0 is the head at the fork.")]
        private RoadNode[] _queueSlots = new RoadNode[0];

        [SerializeField]
        [Tooltip("Parking slots (road nodes); forward = the direction a parked car faces. Includes slots still to be bought.")]
        private RoadNode[] _parkingSlots = new RoadNode[0];

        [SerializeField]
        [Tooltip("Build plots of the location: bays and parking slots that are bought later.")]
        private BuildPlotView[] _buildPlots = new BuildPlotView[0];

        private readonly List<TrafficZone> _zones = new List<TrafficZone>();

        private RoadNode[] _nodes;
        private RouteGraph _graph;
        private string _graphProblem;
        private RoadNode _mainEntranceNode;
        private RoadNode _serviceEntranceNode;
        private RoadNode[] _servicePointNodes;

        /// <summary>Location id.</summary>
        public string LocationId => _locationId;

        /// <summary>Parking entrance reached from the road (may be null if not assigned).</summary>
        public ServicePointView MainEntrance => _mainEntrance;

        /// <summary>Parking entrance reached after a service (may be null if not assigned).</summary>
        public ServicePointView ServiceEntrance => _serviceEntrance;

        /// <summary>Service points of the location (elements may be null if left empty).</summary>
        public ServicePointView[] ServicePoints => _servicePoints;

        /// <summary>Spawn node (may be null if not assigned).</summary>
        public RoadNode SpawnNode => _spawnNode;

        /// <summary>Number of entry queue slots.</summary>
        public int QueueSlotCount => _queueSlots.Length;

        /// <summary>Number of parking slots, including those still to be bought.</summary>
        public int ParkingSlotCount => _parkingSlots.Length;

        /// <summary>Build plots of the location (elements may be null if left empty).</summary>
        public BuildPlotView[] BuildPlots => _buildPlots;

        /// <summary>Buffer slots per service point (the first point's count; <see cref="Validate"/> checks they match), 0 without points.</summary>
        public int ServiceBufferCapacity =>
            _servicePoints.Length > 0 && _servicePoints[0] != null ? _servicePoints[0].BufferSlots.Length : 0;

        /// <summary>Merge zones referenced by the location's nodes (filled by <see cref="BuildGraph"/>).</summary>
        public IReadOnlyList<TrafficZone> Zones => _zones;

        /// <summary>
        /// Indexes every <see cref="RoadNode"/> below this object and builds the route graph from their connections.
        /// Runs once; later calls return the same graph. Startup only (allocates).
        /// </summary>
        public RouteGraph BuildGraph()
        {
            if (_graph != null)
            {
                return _graph;
            }

            _nodes = GetComponentsInChildren<RoadNode>(true);
            for (int i = 0; i < _nodes.Length; i++)
            {
                _nodes[i].SetIndex(i);
            }

            var graph = new RouteGraph(_nodes.Length);
            for (int i = 0; i < _nodes.Length; i++)
            {
                RoadNode node = _nodes[i];
                RoadNode[] next = node.Next;
                for (int n = 0; n < next.Length; n++)
                {
                    RoadNode target = next[n];
                    if (target == null || target == node)
                    {
                        continue;
                    }

                    if (!IsOwnNode(target))
                    {
                        _graphProblem ??= "Road node '" + node.name + "' links to '" + target.name + "' outside this location";
                        continue;
                    }

                    graph.AddEdge(i, target.Index);
                }

                TrafficZone zone = node.Zone;
                if (zone != null && !_zones.Contains(zone))
                {
                    _zones.Add(zone);
                }
            }

            graph.Build();
            _graph = graph;
            CachePointNodes();
            return _graph;
        }

        /// <summary>Road node with graph index <paramref name="index"/> (after <see cref="BuildGraph"/>).</summary>
        /// <exception cref="InvalidOperationException">Thrown before <see cref="BuildGraph"/>.</exception>
        public RoadNode NodeAt(int index)
        {
            if (_nodes == null)
            {
                throw new InvalidOperationException("LocationLayout '" + name + "': call BuildGraph() first.");
            }

            return _nodes[index];
        }

        /// <summary>
        /// Checks that every reference needed at runtime is assigned and that the road graph supports the whole car flow:
        /// spawn → queue; queue head → main entrance, buffers and points; buffer → point; point → exit and service entrance;
        /// entrances → every parking slot → exit — without driving through a parking slot or a point's spot on the way.
        /// Builds the graph if needed.
        /// </summary>
        /// <param name="problem">Description of the first problem found (with node names), or null.</param>
        /// <returns>True when the layout is complete.</returns>
        public bool Validate(out string problem)
        {
            problem = ValidateReferences();
            if (problem != null)
            {
                return false;
            }

            BuildGraph();
            problem = _graphProblem ?? ValidateRoutes();
            return problem == null;
        }

        /// <summary>True when <paramref name="point"/> works from the start, i.e. it is not inside any build plot's Target.</summary>
        public bool IsBuiltAtStart(ServicePointView point)
        {
            return point != null && FindPlotCovering(point) == null;
        }

        /// <summary>Number of parking slots usable from the start: all slots minus those covered by parking build plots.</summary>
        /// <param name="config">Buildables, to tell parking plots from bay plots.</param>
        public int InitialParkingCapacity(IConfigProvider config)
        {
            if (config == null)
            {
                throw new ArgumentNullException(nameof(config));
            }

            int covered = 0;
            for (int i = 0; i < _buildPlots.Length; i++)
            {
                if (_buildPlots[i] != null
                    && config.TryGetBuildable(_buildPlots[i].PlotId, out BuildableSettings settings)
                    && settings.Kind == BuildableKind.ParkingSlot)
                {
                    covered++;
                }
            }

            return Math.Max(0, _parkingSlots.Length - covered);
        }

        /// <summary>
        /// Checks the build plots against the config: ids are unique and known; a bay plot targets a point of
        /// <see cref="ServicePoints"/> that sits inside its Target and has a Service-kind type; a parking plot targets an
        /// existing slot, no slot is covered twice and the covered slots are the last ones.
        /// </summary>
        /// <param name="config">Buildables and service types.</param>
        /// <param name="problem">Description of the first problem found, or null.</param>
        /// <returns>True when every plot is consistent.</returns>
        public bool ValidateBuildPlots(IConfigProvider config, out string problem)
        {
            if (config == null)
            {
                throw new ArgumentNullException(nameof(config));
            }

            problem = null;
            var plotIds = new HashSet<string>(StringComparer.Ordinal);
            var targets = new HashSet<string>(StringComparer.Ordinal);
            var coveredSlots = new List<int>();
            for (int i = 0; i < _buildPlots.Length && problem == null; i++)
            {
                BuildPlotView plot = _buildPlots[i];
                if (plot == null)
                {
                    problem = "Build Plots element " + i + " is empty";
                }
                else if (string.IsNullOrWhiteSpace(plot.PlotId) || !plotIds.Add(plot.PlotId))
                {
                    problem = "Build plot '" + plot.name + "' has an empty or duplicate Plot Id '" + plot.PlotId + "'";
                }
                else if (!config.TryGetBuildable(plot.PlotId, out BuildableSettings settings))
                {
                    problem = "Build plot '" + plot.name + "': buildable '" + plot.PlotId + "' is not in GameConfig";
                }
                else if (!targets.Add(settings.Kind + ":" + settings.TargetId))
                {
                    problem = "Build plot '" + plot.name + "': another plot already builds '" + settings.TargetId + "'";
                }
                else if (settings.Kind == BuildableKind.ServicePoint)
                {
                    problem = ValidatePointPlot(plot, settings, config);
                }
                else if (settings.PlotDefinition.ParkingSlotIndex >= _parkingSlots.Length)
                {
                    problem = "Build plot '" + plot.name + "' targets parking slot " + settings.TargetId + ", but there are only "
                        + _parkingSlots.Length;
                }
                else
                {
                    coveredSlots.Add(settings.PlotDefinition.ParkingSlotIndex);
                }
            }

            // Why: the traffic grows its lot as slots 0..N-1, so only the last slots can be bought later.
            int firstCovered = _parkingSlots.Length - coveredSlots.Count;
            for (int i = 0; i < coveredSlots.Count && problem == null; i++)
            {
                if (coveredSlots[i] < firstCovered)
                {
                    problem = "Parking build plots must cover the last slots (" + firstCovered + ".." + (_parkingSlots.Length - 1)
                        + "), but one covers slot " + coveredSlots[i];
                }
            }

            return problem == null;
        }

        /// <summary>Resolves a destination into the road node the car should stop at (position + heading).</summary>
        /// <returns>False when the destination does not exist in this layout (bad index, unknown point, unassigned reference).</returns>
        public bool TryResolveNode(in CarDestination destination, out RoadNode node)
        {
            // Why: point nodes are cached by BuildGraph so resolving never calls GetComponent during the game loop.
            BuildGraph();
            switch (destination.Kind)
            {
                case CarDestinationKind.QueueSlot:
                    node = ElementOrNull(_queueSlots, destination.Index);
                    break;
                case CarDestinationKind.BufferSlot:
                    int point = IndexOfServicePoint(destination.PointId);
                    node = point >= 0 ? ElementOrNull(_servicePoints[point].BufferSlots, destination.Index) : null;
                    break;
                case CarDestinationKind.Entrance:
                    node = FindEntranceNode(destination.PointId);
                    break;
                case CarDestinationKind.ParkingSlot:
                    node = ElementOrNull(_parkingSlots, destination.Index);
                    break;
                case CarDestinationKind.Point:
                    int index = IndexOfServicePoint(destination.PointId);
                    node = index >= 0 ? _servicePointNodes[index] : null;
                    break;
                case CarDestinationKind.Exit:
                    node = _exitNode;
                    break;
                default:
                    node = null;
                    break;
            }

            return node != null && IsOwnNode(node);
        }

        private string ValidatePointPlot(BuildPlotView plot, BuildableSettings settings, IConfigProvider config)
        {
            int index = IndexOfServicePoint(settings.TargetId);
            if (index < 0)
            {
                return "Build plot '" + plot.name + "' targets point '" + settings.TargetId + "', which is not in Service Points";
            }

            ServicePointView point = _servicePoints[index];
            if (plot.Target == null || !point.transform.IsChildOf(plot.Target.transform))
            {
                return "Build plot '" + plot.name + "': point '" + point.name + "' must be inside the plot's Target";
            }

            if (!config.TryGetServiceType(point.ServiceTypeId, out ServiceTypeSettings type) || type.Kind != PointKind.Service)
            {
                return "Point '" + point.name + "' of build plot '" + plot.name + "': service type '" + point.ServiceTypeId
                    + "' is not a Service type in GameConfig";
            }

            return null;
        }

        private BuildPlotView FindPlotCovering(ServicePointView point)
        {
            for (int i = 0; i < _buildPlots.Length; i++)
            {
                BuildPlotView plot = _buildPlots[i];
                if (plot != null && plot.Target != null && point.transform.IsChildOf(plot.Target.transform))
                {
                    return plot;
                }
            }

            return null;
        }

        private string ValidateReferences()
        {
            if (string.IsNullOrWhiteSpace(_locationId))
            {
                return "Location Id is empty";
            }

            string problem = ValidatePoint(_mainEntrance, "Main Entrance") ?? ValidatePoint(_serviceEntrance, "Service Entrance");
            if (problem != null)
            {
                return problem;
            }

            if (_mainEntrance == _serviceEntrance)
            {
                return "Main and Service Entrance must be different points";
            }

            if (_spawnNode == null)
            {
                return "Spawn Node is not assigned";
            }

            if (_exitNode == null)
            {
                return "Exit Node is not assigned";
            }

            if (_queueSlots.Length == 0)
            {
                return "Queue Slots is empty";
            }

            if (IndexOfNull(_queueSlots) >= 0)
            {
                return "Queue Slots element " + IndexOfNull(_queueSlots) + " is empty";
            }

            if (IndexOfNull(_parkingSlots) >= 0)
            {
                return "Parking Slots element " + IndexOfNull(_parkingSlots) + " is empty";
            }

            for (int i = 0; i < _servicePoints.Length; i++)
            {
                ServicePointView point = _servicePoints[i];
                problem = ValidatePoint(point, "Service Points element " + i);
                if (problem != null)
                {
                    return problem;
                }

                RoadNode[] buffer = point.BufferSlots;
                if (IndexOfNull(buffer) >= 0)
                {
                    return "Point '" + point.name + "': Buffer Slots element " + IndexOfNull(buffer) + " is empty";
                }

                // Why: the traffic logic keeps one buffer capacity per location.
                if (buffer.Length != ServiceBufferCapacity)
                {
                    return "Point '" + point.name + "' has " + buffer.Length + " buffer slots, but '" + _servicePoints[0].name
                        + "' has " + ServiceBufferCapacity + "; every service point needs the same number";
                }
            }

            return null;
        }

        private static string ValidatePoint(ServicePointView point, string label)
        {
            if (point == null)
            {
                return label + " is not assigned";
            }

            if (point.CarSpot == null)
            {
                return "Point '" + point.name + "' has no Car Spot";
            }

            if (!point.CarSpot.TryGetComponent(out RoadNode _))
            {
                return "Car Spot '" + point.CarSpot.name + "' of point '" + point.name + "' has no RoadNode";
            }

            return null;
        }

        private string ValidateRoutes()
        {
            string problem = RequireOwn(_spawnNode, "Spawn node")
                ?? RequireOwn(_exitNode, "Exit node")
                ?? RequireOwn(_mainEntranceNode, "Car spot")
                ?? RequireOwn(_serviceEntranceNode, "Car spot")
                ?? RequireOwnNodes(_queueSlots, "Queue slot")
                ?? RequireOwnNodes(_parkingSlots, "Parking slot")
                ?? RequireOwnNodes(_servicePointNodes, "Car spot");
            for (int i = 0; i < _servicePoints.Length && problem == null; i++)
            {
                problem = RequireOwnNodes(_servicePoints[i].BufferSlots, "Buffer slot");
            }

            if (problem != null)
            {
                return problem;
            }

            // Why: a car that stops at a slot or a spot must never be routed THROUGH one — it would drive across a parked
            // car, a busy bay or a closed barrier. On equal routes the graph prefers earlier connections (through lane first).
            var stops = new HashSet<RoadNode>(_parkingSlots) { _mainEntranceNode, _serviceEntranceNode };
            for (int i = 0; i < _servicePointNodes.Length; i++)
            {
                stops.Add(_servicePointNodes[i]);
            }

            var path = new List<int>(_nodes.Length);
            RoadNode head = _queueSlots[0];
            for (int i = 0; i < _queueSlots.Length && problem == null; i++)
            {
                problem = CheckRoute(_spawnNode, _queueSlots[i], stops, path);
            }

            problem ??= CheckRoute(head, _mainEntranceNode, stops, path);
            for (int i = 0; i < _parkingSlots.Length && problem == null; i++)
            {
                problem = CheckRoute(_mainEntranceNode, _parkingSlots[i], stops, path)
                    ?? CheckRoute(_serviceEntranceNode, _parkingSlots[i], stops, path)
                    ?? CheckRoute(_parkingSlots[i], _exitNode, stops, path);
            }

            for (int i = 0; i < _servicePoints.Length && problem == null; i++)
            {
                RoadNode point = _servicePointNodes[i];
                RoadNode[] buffer = _servicePoints[i].BufferSlots;
                problem = CheckRoute(head, point, stops, path)
                    ?? CheckRoute(point, _exitNode, stops, path)
                    ?? CheckRoute(point, _serviceEntranceNode, stops, path);
                for (int slot = 0; slot < buffer.Length && problem == null; slot++)
                {
                    problem = CheckRoute(head, buffer[slot], stops, path)
                        ?? CheckRoute(buffer[slot], slot == 0 ? point : buffer[slot - 1], stops, path);
                }
            }

            return problem;
        }

        private string CheckRoute(RoadNode from, RoadNode to, HashSet<RoadNode> stops, List<int> path)
        {
            if (!_graph.TryGetPath(from.Index, to.Index, path))
            {
                return "No road route from '" + from.name + "' to '" + to.name + "'";
            }

            for (int i = 0; i < path.Count - 1; i++)
            {
                RoadNode via = _nodes[path[i]];
                if (stops.Contains(via))
                {
                    return "The road route from '" + from.name + "' to '" + to.name + "' drives through '" + via.name
                        + "'; reorder Next (through lane first) or add a bypass";
                }
            }

            return null;
        }

        private string RequireOwn(RoadNode node, string label)
        {
            return IsOwnNode(node) ? null : label + " '" + node.name + "' is not a road node below '" + name + "'";
        }

        private string RequireOwnNodes(RoadNode[] nodes, string label)
        {
            for (int i = 0; i < nodes.Length; i++)
            {
                string problem = RequireOwn(nodes[i], label);
                if (problem != null)
                {
                    return problem;
                }
            }

            return null;
        }

        private bool IsOwnNode(RoadNode node)
        {
            int index = node.Index;
            return _nodes != null && index >= 0 && index < _nodes.Length && _nodes[index] == node;
        }

        private void CachePointNodes()
        {
            _mainEntranceNode = CarSpotNode(_mainEntrance);
            _serviceEntranceNode = CarSpotNode(_serviceEntrance);
            _servicePointNodes = new RoadNode[_servicePoints.Length];
            for (int i = 0; i < _servicePoints.Length; i++)
            {
                _servicePointNodes[i] = CarSpotNode(_servicePoints[i]);
            }
        }

        private static RoadNode CarSpotNode(ServicePointView point)
        {
            if (point == null || point.CarSpot == null)
            {
                return null;
            }

            point.CarSpot.TryGetComponent(out RoadNode node);
            return node;
        }

        private RoadNode FindEntranceNode(string pointId)
        {
            if (_mainEntrance != null && string.Equals(_mainEntrance.PointId, pointId, StringComparison.Ordinal))
            {
                return _mainEntranceNode;
            }

            if (_serviceEntrance != null && string.Equals(_serviceEntrance.PointId, pointId, StringComparison.Ordinal))
            {
                return _serviceEntranceNode;
            }

            return null;
        }

        // Why: a linear scan over a handful of points with ordinal comparison — no dictionary to keep in sync, no allocations.
        private int IndexOfServicePoint(string pointId)
        {
            for (int i = 0; i < _servicePoints.Length; i++)
            {
                ServicePointView point = _servicePoints[i];
                if (point != null && string.Equals(point.PointId, pointId, StringComparison.Ordinal))
                {
                    return i;
                }
            }

            return -1;
        }

        private static RoadNode ElementOrNull(RoadNode[] slots, int index)
        {
            return index >= 0 && index < slots.Length ? slots[index] : null;
        }

        private static int IndexOfNull(RoadNode[] slots)
        {
            for (int i = 0; i < slots.Length; i++)
            {
                if (slots[i] == null)
                {
                    return i;
                }
            }

            return -1;
        }

        private void OnDrawGizmos()
        {
            DrawSlots(_queueSlots, Color.yellow, "Q");
            DrawSlots(_parkingSlots, Color.green, "P");
            for (int i = 0; i < _servicePoints.Length; i++)
            {
                if (_servicePoints[i] != null)
                {
                    DrawSlots(_servicePoints[i].BufferSlots, new Color(1f, 0.6f, 0.1f), "B");
                }
            }

            DrawEndpoint(_spawnNode, Color.blue, "Spawn");
            DrawEndpoint(_exitNode, Color.red, "Exit");
        }

        private static void DrawSlots(RoadNode[] slots, Color color, string prefix)
        {
            Gizmos.color = color;
            for (int i = 0; i < slots.Length; i++)
            {
                RoadNode slot = slots[i];
                if (slot == null)
                {
                    continue;
                }

                Transform slotTransform = slot.transform;
                Gizmos.DrawWireSphere(slotTransform.position, SlotGizmoRadius);
                Gizmos.DrawLine(slotTransform.position, slotTransform.position + slotTransform.forward * 2f);
                DrawLabel(slotTransform.position, prefix + i);
            }
        }

        private static void DrawEndpoint(RoadNode node, Color color, string label)
        {
            if (node == null)
            {
                return;
            }

            Transform point = node.transform;
            Gizmos.color = color;
            Gizmos.DrawWireSphere(point.position, SlotGizmoRadius);
            Gizmos.DrawLine(point.position, point.position + point.forward * 2f);
            DrawLabel(point.position, label);
        }

        // Why: above the node's own name label, so "slot 0" and the node name do not overlap.
        private static void DrawLabel(Vector3 position, string text)
        {
#if UNITY_EDITOR
            UnityEditor.Handles.Label(position + Vector3.up * 1.6f, text);
#endif
        }
    }
}
