using System;
using System.Collections.Generic;
using AutoService.Domain.Traffic.Routing;
using AutoService.Presentation.Points;
using AutoService.Presentation.Traffic.Routing;
using AutoService.Services.Traffic;
using UnityEngine;
using UnityEngine.Serialization;

namespace AutoService.Presentation.Traffic
{
    /// <summary>
    /// Scene markup of one location: its points, its one-way road graph (<see cref="RoadNode"/>s below this object),
    /// spawn/exit nodes, entry queue slots and parking slots. Resolves engine-agnostic <see cref="CarDestination"/>s into
    /// road nodes and builds the <see cref="RouteGraph"/> cars drive on.
    /// </summary>
    /// <remarks>
    /// Every point's Car Spot carries a <see cref="RoadNode"/>, so a point is just another node of the graph.
    /// Whitebox layout v2 is generated by <c>AutoService → Whitebox → Build Location 1 Roads</c> (GDD §3).
    /// </remarks>
    public sealed class LocationLayout : MonoBehaviour
    {
        private const float SlotGizmoRadius = 0.6f;

        [SerializeField]
        [Tooltip("Location id; every point of this location gets it as LocationId, e.g. \"loc1\".")]
        private string _locationId = string.Empty;

        [SerializeField, FormerlySerializedAs("_barrier")]
        [Tooltip("The parking exit barrier point (Service Type of kind Barrier): every car leaving the lot pays there.")]
        private ServicePointView _parkingExit;

        [SerializeField]
        [Tooltip("Service points of the location (wash...). Not the parking exit.")]
        private ServicePointView[] _servicePoints = new ServicePointView[0];

        [SerializeField]
        [Tooltip("Road node where cars appear; its forward is their initial heading.")]
        private RoadNode _spawnNode;

        [SerializeField]
        [Tooltip("Road node where leaving cars drive to and disappear.")]
        private RoadNode _exitNode;

        [SerializeField]
        [Tooltip("Entry queue lane slots (road nodes); element 0 is the head at the fork.")]
        private RoadNode[] _queueSlots = new RoadNode[0];

        [SerializeField]
        [Tooltip("Parking slots (road nodes); forward = the direction a parked car faces.")]
        private RoadNode[] _parkingSlots = new RoadNode[0];

        private readonly List<TrafficZone> _zones = new List<TrafficZone>();

        private RoadNode[] _nodes;
        private RouteGraph _graph;
        private string _graphProblem;
        private RoadNode _parkingExitNode;
        private RoadNode[] _servicePointNodes;

        /// <summary>Location id.</summary>
        public string LocationId => _locationId;

        /// <summary>The parking exit barrier point (may be null if not assigned).</summary>
        public ServicePointView ParkingExit => _parkingExit;

        /// <summary>Service points of the location (elements may be null if left empty).</summary>
        public ServicePointView[] ServicePoints => _servicePoints;

        /// <summary>Spawn node (may be null if not assigned).</summary>
        public RoadNode SpawnNode => _spawnNode;

        /// <summary>Number of entry queue slots.</summary>
        public int QueueSlotCount => _queueSlots.Length;

        /// <summary>Number of parking slots.</summary>
        public int ParkingSlotCount => _parkingSlots.Length;

        /// <summary>Merge zones referenced by the location's nodes (filled by <see cref="BuildGraph"/>).</summary>
        public IReadOnlyList<TrafficZone> Zones => _zones;

        /// <summary>
        /// Indexes every <see cref="RoadNode"/> below this object and builds the route graph from their connections.
        /// Runs once; later calls return the same graph. Startup only (allocates).
        /// </summary>
        public RouteGraph BuildGraph()
        {
            if (_graph != null)
            {
                return _graph;
            }

            _nodes = GetComponentsInChildren<RoadNode>(true);
            for (int i = 0; i < _nodes.Length; i++)
            {
                _nodes[i].SetIndex(i);
            }

            var graph = new RouteGraph(_nodes.Length);
            for (int i = 0; i < _nodes.Length; i++)
            {
                RoadNode node = _nodes[i];
                RoadNode[] next = node.Next;
                for (int n = 0; n < next.Length; n++)
                {
                    RoadNode target = next[n];
                    if (target == null || target == node)
                    {
                        continue;
                    }

                    if (!IsOwnNode(target))
                    {
                        _graphProblem ??= "Road node '" + node.name + "' links to '" + target.name + "' outside this location";
                        continue;
                    }

                    graph.AddEdge(i, target.Index);
                }

                TrafficZone zone = node.Zone;
                if (zone != null && !_zones.Contains(zone))
                {
                    _zones.Add(zone);
                }
            }

            graph.Build();
            _graph = graph;
            CachePointNodes();
            return _graph;
        }

        /// <summary>Road node with graph index <paramref name="index"/> (after <see cref="BuildGraph"/>).</summary>
        /// <exception cref="InvalidOperationException">Thrown before <see cref="BuildGraph"/>.</exception>
        public RoadNode NodeAt(int index)
        {
            if (_nodes == null)
            {
                throw new InvalidOperationException("LocationLayout '" + name + "': call BuildGraph() first.");
            }

            return _nodes[index];
        }

        /// <summary>
        /// Checks that every reference needed at runtime is assigned and that the road graph supports the whole car flow:
        /// spawn → every slot, queue head → every point, parking slots → parking exit → points and exit, points → exit,
        /// without driving through a parking slot or a point's spot on the way. Builds the graph if needed.
        /// </summary>
        /// <param name="problem">Description of the first problem found (with node names), or null.</param>
        /// <returns>True when the layout is complete.</returns>
        public bool Validate(out string problem)
        {
            problem = ValidateReferences();
            if (problem != null)
            {
                return false;
            }

            BuildGraph();
            problem = _graphProblem ?? ValidateRoutes();
            return problem == null;
        }

        /// <summary>Resolves a destination into the road node the car should stop at (position + heading).</summary>
        /// <returns>False when the destination does not exist in this layout (bad index, unknown point, unassigned reference).</returns>
        public bool TryResolveNode(in CarDestination destination, out RoadNode node)
        {
            // Why: point nodes are cached by BuildGraph so resolving never calls GetComponent during the game loop.
            BuildGraph();
            switch (destination.Kind)
            {
                case CarDestinationKind.QueueSlot:
                    node = ElementOrNull(_queueSlots, destination.Index);
                    break;
                case CarDestinationKind.ParkingSlot:
                    node = ElementOrNull(_parkingSlots, destination.Index);
                    break;
                case CarDestinationKind.ParkingExit:
                    node = _parkingExitNode;
                    break;
                case CarDestinationKind.Point:
                    node = FindPointNode(destination.PointId);
                    break;
                case CarDestinationKind.Exit:
                    node = _exitNode;
                    break;
                default:
                    node = null;
                    break;
            }

            return node != null && IsOwnNode(node);
        }

        private string ValidateReferences()
        {
            if (string.IsNullOrWhiteSpace(_locationId))
            {
                return "Location Id is empty";
            }

            string pointProblem = ValidatePoint(_parkingExit, "Parking Exit");
            if (pointProblem != null)
            {
                return pointProblem;
            }

            if (_spawnNode == null)
            {
                return "Spawn Node is not assigned";
            }

            if (_exitNode == null)
            {
                return "Exit Node is not assigned";
            }

            if (_queueSlots.Length == 0)
            {
                return "Queue Slots is empty";
            }

            if (IndexOfNull(_queueSlots) >= 0)
            {
                return "Queue Slots element " + IndexOfNull(_queueSlots) + " is empty";
            }

            if (IndexOfNull(_parkingSlots) >= 0)
            {
                return "Parking Slots element " + IndexOfNull(_parkingSlots) + " is empty";
            }

            for (int i = 0; i < _servicePoints.Length; i++)
            {
                pointProblem = ValidatePoint(_servicePoints[i], "Service Points element " + i);
                if (pointProblem != null)
                {
                    return pointProblem;
                }
            }

            return null;
        }

        private static string ValidatePoint(ServicePointView point, string label)
        {
            if (point == null)
            {
                return label + " is not assigned";
            }

            if (point.CarSpot == null)
            {
                return "Point '" + point.name + "' has no Car Spot";
            }

            if (!point.CarSpot.TryGetComponent(out RoadNode _))
            {
                return "Car Spot '" + point.CarSpot.name + "' of point '" + point.name + "' has no RoadNode";
            }

            return null;
        }

        private string ValidateRoutes()
        {
            if (!IsOwnNode(_spawnNode) || !IsOwnNode(_exitNode))
            {
                return "Spawn and Exit nodes must be road nodes below '" + name + "'";
            }

            string problem = RequireOwnNodes(_queueSlots, "Queue slot")
                ?? RequireOwnNodes(_parkingSlots, "Parking slot")
                ?? RequireOwnNodes(_servicePointNodes, "Car spot")
                ?? (IsOwnNode(_parkingExitNode) ? null : "Car spot '" + _parkingExitNode.name + "' is not a road node below '" + name + "'");
            if (problem != null)
            {
                return problem;
            }

            // Why: a car that stops at a slot or a spot must never be routed THROUGH one — it would drive across a parked
            // car or a busy bay. On equal routes the graph prefers earlier connections (through lane first).
            var stops = new HashSet<RoadNode>(_parkingSlots) { _parkingExitNode };
            for (int i = 0; i < _servicePointNodes.Length; i++)
            {
                stops.Add(_servicePointNodes[i]);
            }

            var path = new List<int>(_nodes.Length);
            RoadNode head = _queueSlots[0];
            for (int i = 0; i < _queueSlots.Length && problem == null; i++)
            {
                problem = CheckRoute(_spawnNode, _queueSlots[i], stops, path);
            }

            for (int i = 0; i < _parkingSlots.Length && problem == null; i++)
            {
                problem = CheckRoute(_spawnNode, _parkingSlots[i], stops, path)
                    ?? CheckRoute(head, _parkingSlots[i], stops, path)
                    ?? CheckRoute(_parkingSlots[i], _parkingExitNode, stops, path);
            }

            for (int i = 0; i < _servicePointNodes.Length && problem == null; i++)
            {
                RoadNode point = _servicePointNodes[i];
                problem = CheckRoute(head, point, stops, path)
                    ?? CheckRoute(_parkingExitNode, point, stops, path)
                    ?? CheckRoute(point, _exitNode, stops, path);
            }

            return problem ?? CheckRoute(_parkingExitNode, _exitNode, stops, path);
        }

        private string CheckRoute(RoadNode from, RoadNode to, HashSet<RoadNode> stops, List<int> path)
        {
            if (!_graph.TryGetPath(from.Index, to.Index, path))
            {
                return "No road route from '" + from.name + "' to '" + to.name + "'";
            }

            for (int i = 0; i < path.Count - 1; i++)
            {
                RoadNode via = _nodes[path[i]];
                if (stops.Contains(via))
                {
                    return "The road route from '" + from.name + "' to '" + to.name + "' drives through '" + via.name
                        + "'; reorder Next (through lane first) or add a bypass";
                }
            }

            return null;
        }

        private string RequireOwnNodes(RoadNode[] nodes, string label)
        {
            for (int i = 0; i < nodes.Length; i++)
            {
                if (!IsOwnNode(nodes[i]))
                {
                    return label + " '" + nodes[i].name + "' is not a road node below '" + name + "'";
                }
            }

            return null;
        }

        private bool IsOwnNode(RoadNode node)
        {
            int index = node.Index;
            return _nodes != null && index >= 0 && index < _nodes.Length && _nodes[index] == node;
        }

        private void CachePointNodes()
        {
            _parkingExitNode = CarSpotNode(_parkingExit);
            _servicePointNodes = new RoadNode[_servicePoints.Length];
            for (int i = 0; i < _servicePoints.Length; i++)
            {
                _servicePointNodes[i] = CarSpotNode(_servicePoints[i]);
            }
        }

        private static RoadNode CarSpotNode(ServicePointView point)
        {
            if (point == null || point.CarSpot == null)
            {
                return null;
            }

            point.CarSpot.TryGetComponent(out RoadNode node);
            return node;
        }

        // Why: a linear scan over a handful of points with ordinal comparison — no dictionary to keep in sync, no allocations.
        private RoadNode FindPointNode(string pointId)
        {
            if (_parkingExit != null && string.Equals(_parkingExit.PointId, pointId, StringComparison.Ordinal))
            {
                return _parkingExitNode;
            }

            for (int i = 0; i < _servicePoints.Length; i++)
            {
                ServicePointView point = _servicePoints[i];
                if (point != null && string.Equals(point.PointId, pointId, StringComparison.Ordinal))
                {
                    return _servicePointNodes[i];
                }
            }

            return null;
        }

        private static RoadNode ElementOrNull(RoadNode[] slots, int index)
        {
            return index >= 0 && index < slots.Length ? slots[index] : null;
        }

        private static int IndexOfNull(RoadNode[] slots)
        {
            for (int i = 0; i < slots.Length; i++)
            {
                if (slots[i] == null)
                {
                    return i;
                }
            }

            return -1;
        }

        private void OnDrawGizmos()
        {
            DrawSlots(_queueSlots, Color.yellow, "Q");
            DrawSlots(_parkingSlots, Color.green, "P");
            DrawEndpoint(_spawnNode, Color.blue, "Spawn");
            DrawEndpoint(_exitNode, Color.red, "Exit");
        }

        private static void DrawSlots(RoadNode[] slots, Color color, string prefix)
        {
            Gizmos.color = color;
            for (int i = 0; i < slots.Length; i++)
            {
                RoadNode slot = slots[i];
                if (slot == null)
                {
                    continue;
                }

                Transform slotTransform = slot.transform;
                Gizmos.DrawWireSphere(slotTransform.position, SlotGizmoRadius);
                Gizmos.DrawLine(slotTransform.position, slotTransform.position + slotTransform.forward * 2f);
                DrawLabel(slotTransform.position, prefix + i);
            }
        }

        private static void DrawEndpoint(RoadNode node, Color color, string label)
        {
            if (node == null)
            {
                return;
            }

            Transform point = node.transform;
            Gizmos.color = color;
            Gizmos.DrawWireSphere(point.position, SlotGizmoRadius);
            Gizmos.DrawLine(point.position, point.position + point.forward * 2f);
            DrawLabel(point.position, label);
        }

        // Why: above the node's own name label, so "slot 0" and the node name do not overlap.
        private static void DrawLabel(Vector3 position, string text)
        {
#if UNITY_EDITOR
            UnityEditor.Handles.Label(position + Vector3.up * 1.6f, text);
#endif
        }
    }
}
